#!/usr/bin/env node
/**
 * Install the harness declaration tree that a compatibility gate type-checks against.
 *
 * `npm run compat:0.2.0` needs no install step: this repository's own
 * `node_modules` already *is* 0.2.0-rc.2. The 0.1.7 line is different — it must
 * not be the tree the ordinary check runs on, so its gate reads a private install
 * under the gitignored `_scratch/`.
 *
 * Two things this script exists to get right:
 *
 *   1. **npm does not walk upwards for `.npmrc`.** Run from `_scratch/<dir>`, npm
 *      would use the default cache — outside this workspace's write sandbox —
 *      and die with `EPERM` before any network work happens (measured, 2026-10-07;
 *      see IS-072). So the tree gets its own `.npmrc` carrying the repository's
 *      cache redirect, written out with an absolute path.
 *   2. **The install is idempotent.** A marker records the exact version set that
 *      was installed; a second run type-checks immediately instead of hitting the
 *      registry again. `--force` reinstalls.
 *
 * `cordis` / `schemastery` do not follow the DSH version line (IS-062), so their
 * pins are read from this repository's `devDependencies` — one home, so bumping
 * one of them cannot make the two gates disagree about it.
 *
 * Usage: node tools/compat-install.mjs <version> [--force]
 *
 * @module tools/compat-install
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

const args = process.argv.slice(2)
const force = args.includes('--force')
const version = args.find((arg) => !arg.startsWith('--'))

if (version === undefined) {
  console.error('usage: node tools/compat-install.mjs <version> [--force]')
  process.exit(2)
}

/** Packages that follow the DSH version line; all pinned to the requested version. */
const VERSION_LINE_PACKAGES = ['@deepseek-ai/dsh-session', '@deepseek-ai/dsh-agent']

/** Packages pinned independently of the DSH version line (IS-062). */
const INDEPENDENT_PACKAGES = ['@deepseek-ai/cordis', '@deepseek-ai/schemastery']

const manifest = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
/** @type {Record<string, string>} */
const devDependencies = manifest.devDependencies ?? {}

const dependencies = Object.fromEntries([
  ...VERSION_LINE_PACKAGES.map((name) => [name, version]),
  ...INDEPENDENT_PACKAGES.map((name) => {
    const pin = devDependencies[name]
    if (pin === undefined) {
      console.error(`compat-install: package.json has no devDependencies["${name}"] to reuse`)
      process.exit(2)
    }
    return [name, pin]
  }),
])

const target = join(root, '_scratch', `compat-${version}`)
const marker = join(target, '.installed.json')
const wanted = JSON.stringify(dependencies)

if (!force && existsSync(marker) && readFileSync(marker, 'utf8') === wanted) {
  console.log(`compat-install: ${target} already holds ${describeDependencies()} (use --force to reinstall)`)
  process.exit(0)
}

mkdirSync(target, { recursive: true })

// The private install's own project config. `cache` must be absolute: this file
// lives two levels down, so the repository-relative form in the root `.npmrc`
// would resolve to the wrong place.
writeFileSync(
  join(target, '.npmrc'),
  [
    `# Generated by tools/compat-install.mjs — do not edit.`,
    `# npm resolves project config from the current directory only (no upward walk),`,
    `# so the repository-root .npmrc does not apply down here (IS-072).`,
    `cache=${join(root, '.npm-cache')}`,
    'audit=false',
    'fund=false',
    '',
  ].join('\n'),
  'utf8',
)

writeFileSync(
  join(target, 'package.json'),
  JSON.stringify(
    {
      name: `compat-gate-${version}`,
      private: true,
      version: '0.0.0',
      type: 'module',
      description: `Harness declarations for the ${version} compatibility gate. Generated, not published.`,
      devDependencies: dependencies,
    },
    null,
    2,
  ) + '\n',
  'utf8',
)

console.log(`compat-install: installing ${describeDependencies()} into ${target}`)

const result = runNpmInstall(target)

if (result.error !== undefined) {
  console.error(`compat-install: could not run npm: ${result.error.message}`)
  process.exit(1)
}
if (result.status !== 0) {
  console.error(`compat-install: npm install failed (exit ${result.status})`)
  process.exit(result.status ?? 1)
}

writeFileSync(marker, wanted, 'utf8')
console.log(`compat-install: ready — ${target}`)

/**
 * Run `npm install` in the private tree.
 *
 * Under `npm run`, `npm_execpath` is npm's own CLI entry, so node can run it
 * directly: no shell, no `.cmd` shim, and none of the argument-concatenation
 * caveat that `shell: true` carries (measured: that shape warns with DEP0190).
 * Invoked directly (`node tools/compat-install.mjs …`) there is no such path and
 * npm's `.cmd` shim needs a shell on Windows.
 *
 * @param cwd - the private tree to install into.
 * @returns the finished child process.
 */
function runNpmInstall(cwd) {
  const npmCli = process.env.npm_execpath
  if (npmCli !== undefined && npmCli !== '' && existsSync(npmCli)) {
    return spawnSync(process.execPath, [npmCli, 'install'], { cwd, stdio: 'inherit' })
  }
  return spawnSync('npm install', { cwd, stdio: 'inherit', shell: true })
}

/** Render the dependency set for a one-line log message. */
function describeDependencies() {
  return Object.entries(dependencies)
    .map(([name, pin]) => `${name.replace('@deepseek-ai/', '')}@${pin}`)
    .join(' + ')
}
